pretrained_model_path: "timbrooks/instruct-pix2pix"
ddim_source: "CompVis/stable-diffusion-v1-4"
output_dir: "./output/face"

train_data:
  data_path: "data/face"
  prompt: ""
  width: 512
  height: 512

validation_data:
  prompts:
    - "Turn him into Batman"
  video_length: 10
  width: 512
  height: 512
  num_inference_steps: 20
  guidance_scale: 7.5
  image_guidance_scale: 1.3
  use_inv_latent: True
  num_inv_steps: 20

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 90
validation_steps: 10
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
