pretrained_model_path: "timbrooks/instruct-pix2pix"
ddim_source: "CompVis/stable-diffusion-v1-4"
output_dir: "./output/penguin_cam"

train_data:
  data_path: "./data/penguin_360.mp4"
  prompt: "turn it into a penguin"
  n_sample_frames: 20
  width: 512
  height: 256
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "turn it into a panda"
  video_length: 20
  width: 512
  height: 256
  num_inference_steps: 50
  guidance_scale: 10
  image_guidance_scale: 1.3
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 300
validation_steps: 30
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
